#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Lingua-Translit
Version  : 0.28
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AL/ALINKE/Lingua-Translit-0.28.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AL/ALINKE/Lingua-Translit-0.28.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libl/liblingua-translit-perl/liblingua-translit-perl_0.28-1.debian.tar.xz
Summary  : transliterates text between writing systems
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Lingua-Translit-bin
Requires: perl-Lingua-Translit-man

%description
Perl Module Lingua::Translit
----------------------------
ABOUT
Lingua::Translit can be used to convert text from one writing system to
another, based on national or international transliteration tables.
Where possible a reverse transliteration is supported.

%package bin
Summary: bin components for the perl-Lingua-Translit package.
Group: Binaries
Requires: perl-Lingua-Translit-man

%description bin
bin components for the perl-Lingua-Translit package.


%package man
Summary: man components for the perl-Lingua-Translit package.
Group: Default

%description man
man components for the perl-Lingua-Translit package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Lingua-Translit-0.28
mkdir -p %{_topdir}/BUILD/Lingua-Translit-0.28/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Lingua-Translit-0.28/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Lingua/Translit.pm
/usr/lib/perl5/site_perl/5.26.1/Lingua/Translit/Tables.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/translit

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/translit.1
/usr/share/man/man3/Lingua::Translit.3
/usr/share/man/man3/Lingua::Translit::Tables.3
